In [2]:
import pandas as pd

data = pd.read_csv('./creditcard.csv')

print(data.head())

print(data.columns)

valid_purchases = data[data['Class'] == "'0'"].shape[0]
fraudulent_purchases = data[data['Class'] == "'1'"].shape[0]

print("valid purchases:", valid_purchases)
print("raudulent purchases:", fraudulent_purchases)

total_purchases = valid_purchases + fraudulent_purchases

accuracy_when_all_zero = valid_purchases / total_purchases

print("Theoretical Accuracy:", accuracy_when_all_zero)


   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28 

In [4]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['Class'] = label_encoder.fit_transform(data['Class'])

y = data['Class']

y_allZero = np.zeros_like(y)

print("Confusion Matrix:\n", confusion_matrix(y, y_allZero))

Confusion Matrix:
 [[284315      0]
 [   492      0]]


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['Class'] = label_encoder.fit_transform(data['Class'])

X = data.drop('Class', axis=1)
y = data['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=13)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (227845, 30)
Testing set size: (56962, 30)


In [8]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score ,recall_score, precision_score, f1_score

linear_svm = SVC(kernel='linear')
linear_svm.fit(X_train, y_train)
y_pred_linear = linear_svm.predict(X_test)
print("linear_SVM_accuracy:",accuracy_score(y_test, y_pred_linear))
print("linear_SVM_recall:",recall_score(y_test, y_pred_linear))
print("linear_SVM_precision:",precision_score(y_test, y_pred_linear))
print("linear_SVM_f1_score:",f1_score(y_test, y_pred_linear))
# rbf_svm = SVC(kernel='rbf')
# rbf_svm.fit(X_train, y_train)
# y_pred_linear = rbf_svm.predict(X_test)
# print("RBF_SVM_accuracy:",accuracy_score(y_test, y_pred_linear))
# print("RBF_SVM_recall:",recall_score(y_test, y_pred_linear))
# print("RBF_SVM_precision:",precision_score(y_test, y_pred_linear))
# print("RBF_SVM_f1_score:",f1_score(y_test, y_pred_linear))


linear_SVM_accuracy: 0.9984726659878516
linear_SVM_recall: 0.3
linear_SVM_precision: 0.5294117647058824
linear_SVM_f1_score: 0.3829787234042553


In [11]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

y_pred_linear = linear_svm.predict(X_test)


print("SVM Model:\n", confusion_matrix(y_test, y_pred_linear))


y = data['Class']

y_allZero = np.zeros_like(y)

print("Part b:\n", confusion_matrix(y, y_allZero))

SVM Model:
 [[56848    24]
 [   63    27]]
Part b:
 [[284315      0]
 [   492      0]]
